
Showing logs for build [32mmeta-vicky-socs-test-python-jen-zrfjk-7[0m stage [32mmeta-pipeline[0m and container [32mstep-credential-initializer-x7k2k[0m
{"level":"warn","ts":1584610803.7902305,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584610803.7908862,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmeta-vicky-socs-test-python-jen-zrfjk-7[0m stage [32mmeta-pipeline[0m and container [32mstep-working-dir-initializer-gcbhk[0m
{"level":"warn","ts":1584610804.7533255,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1584610804.7554064,"logger":"fallback-logger","caller":"bash/main.go:64","msg":"Successfully executed command \"sh -c mkdir -p /workspace/source\"; output "}

Showing logs for build [32mmeta-vicky-socs-test-python-jen-zrfjk-7[0m stage [32mmeta-pipeline[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmeta-vicky-socs-test-python-jen-zrfjk-7[0m stage [32mmeta-pipeline[0m and container [32mstep-git-source-meta-vicky-socs-test-python-jen-zrfjk-6xnnj[0m
{"level":"warn","ts":1584610810.810482,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/0.8.0-**-support-backwards-incompats\" is not a valid GitHub commit ID"}
{"level":"info","ts":1584610813.4677284,"logger":"fallback-logger","caller":"git/git.go:103","msg":"Successfully cloned https://github.com/vicky-socs/test-python-jenkinsx.git @ ca5033b00cb7be45c89d630cf44d908853c2ba2f in path /workspace/source"}

Showing logs for build [32mmeta-vicky-socs-test-python-jen-zrfjk-7[0m stage [32mmeta-pipeline[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=staging:ca5033b00cb7be45c89d630cf44d908853c2ba2f
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mmeta-vicky-socs-test-python-jen-zrfjk-7[0m stage [32mmeta-pipeline[0m and container [32mstep-merge-pull-refs[0m
SKIP merge-pull-refs: Nothing to merge

Showing logs for build [32mmeta-vicky-socs-test-python-jen-zrfjk-7[0m stage [32mmeta-pipeline[0m and container [32mstep-create-effective-pipeline[0m
error: failed to load project config in dir /workspace/source: failed to validate YAML file /workspace/source/jenkins-x-staging.yml due to yaml: line 2: mapping values are not allowed in this context
[31m
Pipeline failed on stage 'meta-pipeline' : container 'step-create-effective-pipeline'. The execution of the pipeline has stopped.[0m
